### ISSUE TITLE
subdomains are not working

### ISSUE THREAD

**Issue by Noext** [ahembree/ansible-hms-docker#1]
hello 
very nice project
i have use the standar configuration with the home.local example
i can join traefik on home.local:8080 but all other subdomain ( plex.home.local etc ) are not working

**Comment by ahembree** [comment]
Thank you!

In order for the DNS stuff to work, you will need to create those "A" records on your DNS server yourself (or within your `hosts` file on your machine, though this means only the machine you're on will be able to use the FQDN's, so not recommended). Setting up or configuring your own DNS server is outside the scope of this project.

And technically `home.local` [is not a valid TLD](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) according to IANA, so you may need to end the URL with a `/` in order for it to attempt to load a page (if you do actually use `home.local` as your internal domain). I just used `home.local` as an example in the configs as I didn't want to bombard DNS servers with people trying to use `example.com` by default.

If you're unable to modify your DNS records, you can expose the ports of all possible containers (found in the table near the bottom of the readme) by setting this value in your `vars/default.yml` (or changing it in your `roles/hmsdocker/defaults/main.yml`, where all possible settings are): 

`container_expose_ports: yes`
