### ISSUE TITLE
Tailscale not working

### ISSUE THREAD

**Issue by LewisLebentz** [ahembree/ansible-hms-docker#102]
I can't figure out why, but since updating to the latest version of this and migrating vars, it doesn't even seem to attempt to start a Tailscale container. I have checked the old and new vars locations and it is definitely set to be enabled still, but no container is ever started and the make check/apply ansible script doesn't seem to find any changes in that file now.

I suspect some code is missing somewhere, maybe the enabled detection bit or part of the ansible script to turn it on but I'm struggling!

I had no issues with it prior to updating (I was likely a few months out of date)

**Comment by LewisLebentz** [comment]
Probably a separate issue, but maybe related to the migration too - Plex is no longer picking up files from Transmission. So rightly or wrongly, I've just added the folder here and it now works:

![image](https://github.com/user-attachments/assets/59af4a74-3695-407e-882c-249995bf1244)

**Comment by ahembree** [comment]
Thanks for the report about Tailscale not working! This was an oversight with a recent update and should now be resolved in this commit: https://github.com/ahembree/ansible-hms-docker/commit/18123f7531bea9cffc8ae3b3e015abfed7f3ad1e

Please run `git pull` to get the latest code.

As for Plex not picking up Transmission files, the Transmission path should not need to be configured in Plex. This may be an issue with how Sonarr or Radarr is transferring the files once the download completes.

**Comment by ahembree** [comment]
In PR https://github.com/ahembree/ansible-hms-docker/pull/93, files paths were changed quite a bit in order to support hardlinks/atomic moves.

I tried to document some steps to update the configs in the various apps here under section Version 0.2: https://github.com/ahembree/ansible-hms-docker/blob/master/docs/Release%20Notes.md#verison-02

**Comment by LewisLebentz** [comment]
That's fixed it, thank you!

**Comment by KnuffigerMaxi** [comment]
> As for Plex not picking up Transmission files, the Transmission path should not need to be configured in Plex. This may be an issue with how Sonarr or Radarr is transferring the files once the download completes.

Do you have instructions for this?

**Comment by ahembree** [comment]
@KnuffigerMaxi not exactly as everyone's setup is likely different, but this guide is what I followed to configure directory layouts: https://trash-guides.info/File-and-Folder-Structure/Hardlinks-and-Instant-Moves/
