### ISSUE TITLE
replace Overseerr to Jellyseerr 

### ISSUE THREAD

**Issue by KnuffigerMaxi** [ahembree/ansible-hms-docker#103]
Hey, Overseerr is out to date from the last year. 

i think Jellyseerr is newer - a fork of 

Jellyseerr is a free and open source software application for managing requests for your media library. It is a fork of [Overseerr](https://github.com/sct/overseerr) built to bring support for [Jellyfin](https://github.com/jellyfin/jellyfin) & [Emby](https://github.com/MediaBrowser/Emby) media servers!

see here new release for overseerr: https://github.com/sct/overseerr/discussions/3948

**Comment by ahembree** [comment]
I'll investigate adding it alongside Overseerr and letting people choose which to use, but I don't want to fully replace it

**Comment by KnuffigerMaxi** [comment]
Hey @ahembree,
It its the same https://github.com/varthe/Redirecterr of Recyclarr: auto-sync for TRaSH guides ( https://github.com/recyclarr/recyclarr)

**Comment by ahembree** [comment]
This does not look related to Recyclarr, it appears to redirect media requests to different Sonarr or Radarr instances based on certain criteria, whereas Recyclarr syncs media profiles to those instances and is unrelated to Overseerr requests

**Comment by KnuffigerMaxi** [comment]
I can't see it in the inventory/group_all/all/container_map.yml
