### ISSUE TITLE
[ Idea } Feature Request: Add Support for Cross-Seed Integration in Transmission Setup

### ISSUE THREAD

**Issue by KnuffigerMaxi** [ahembree/ansible-hms-docker#107]
### Discussed in https://github.com/ahembree/ansible-hms-docker/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **KnuffigerMaxi** November 27, 2024</sup>
Hi,  
I’ve been using **ansible-hms-docker** to manage my media services and would like to propose enhanced support for integrating [[cross-seed](https://github.com/cross-seed/cross-seed)](https://github.com/cross-seed/cross-seed) with **Transmission**. Cross-seed is a tool that helps discover torrents from multiple trackers, improving redundancy and download speeds.

### Issue  
Currently, in my setup with **Transmission 4.0.5 (a6fe2a64aa)**, RPC 17, and WEB Control 1.6.1 (20200913), cross-seed organizes torrents into subdirectories based on tracker names, like this:

```bash
cat:
  movies-hd: /data/.torrents/movies/hd
  movies-uhd: /data/.torrents/movies/uhd
  cross-seed: /data/.torrents/movies/cross-seed
  HDB: /data/.torrents/movies/cross-seed/HDB/
  ATH: /data/.torrents/movies/cross-seed/ATH/
  MTV: /data/.torrents/movies/cross-seed/MTV/
  TL: /data/.torrents/movies/cross-seed/TL/
  BLU: /data/.torrents/movies/cross-seed/BLU/
```

However, cross-seed’s default category system and Transmission's behavior don’t align perfectly. Transmission lacks built-in support for tracker-specific categorization and instead organizes torrents broadly, which complicates integration.

### Proposed Solution  
1. **Customizable Category Mapping:** Add configuration options to allow Transmission to map cross-seed’s subdirectories (based on tracker names) to categories in Transmission.
2. **Directory Auto-Discovery:** Enable automatic scanning of `/data/torrents/movies/cross-seed` for new tracker subdirectories created by cross-seed.
3. **RPC Adjustments:** Improve RPC settings to sync with cross-seed’s torrent addition methods.

### Benefits  
- Simplifies torrent organization for cross-seed users in Transmission.  
- Enables better alignment with cross-seed’s tracker-based directory structure.  
- Streamlines automation for seedbox setups.

### References  
- [[Cross-seed GitHub Repository](https://github.com/cross-seed/cross-seed)](https://github.com/cross-seed/cross-seed)  
- [[Cross-seed Basics: Getting Started](https://www.cross-seed.org/docs/basics/getting-started)](https://www.cross-seed.org/docs/basics/getting-started)  
- [[Transmission RPC Protocol](https://github.com/transmission/transmission/wiki/RPC-Protocol)](https://github.com/transmission/transmission/wiki/RPC-Protocol)  
</div>

**Comment by ahembree** [comment]
Not an Issue, already posted as Discussion
