### ISSUE TITLE
Question about DNS

### ISSUE THREAD

**Issue by mrkaffeine92** [ahembree/ansible-hms-docker#15]
Hi, I purchased a Domain on GoDaddy. How can I integrate it into the config file? I am not sure how to setup the WildCard with CloudFlare as I am someone new to Domains and SSL. Can you kindly advise how to set everything up to at least get started?

**Comment by ahembree** [comment]
Hey @mrkaffeine92,

Since GoDaddy is your registrar, you will need to configure a setting within GoDaddy to use Cloudflare as your Nameservers, assuming you already have your Cloudflare account setup: https://www.godaddy.com/help/edit-my-domain-nameservers-664.

Once Cloudflare is set as your Nameservers, you can then setup the API keys within Cloudflare and add them to the config file. After this is completed, re-run the ansible commands and it'll update all templates and stuff. It takes a few minutes for the SSL to generate I believe.

**Comment by mrkaffeine92** [comment]
Thank you kindly for the quick response. I have put in a request to GoDaddy to update the NameServers to Cloudflare. Once I hear back confirmation, I will continue with the tutorial.

Thank you :-)

------- Original Message -------

**Comment by mrkaffeine92** [comment]
Hi, can you please kindly advise:

{
"CF_DNS_API_TOKEN": "{{ xx }}", # Example cloudflare environment variable, can use the same API token as the one for DDNS
"CF_ZONE_API_TOKEN": "{{ xx }}", # Example cloudflare environment variable, can use the same API token as the one for DDNS }

# Your Cloudflare API token that has read/write permissions for your DNS zone
# This will also be provided to Traefik if using SSL (assuming Cloudflare is your DNS provider)
cloudflare_api_token: "xx"

--this is ALL meant to be the API Key when we click "View Global API Key" on Cloudflare?

The other question is:
The support thread requests to run:

CLOUDFLARE_EMAIL

=

***@***.***"

\

CLOUDFLARE_API_KEY

=

"yourprivatecloudflareapikey"

\

lego --email

***@***.***"

--dns cloudflare --domains

"example.org"

run

Why do I run this if I have the API keys already? I ran it with the earlier Global API key and get errors..

------- Original Message -------

**Comment by ahembree** [comment]
You can generate a "scoped" API token following the guide here: https://developers.cloudflare.com/fundamentals/api/get-started/create-token/

If that command is from GoDaddy, I'm unsure and am unable to provide any help as I'm not familiar with their platform.

**Comment by mrkaffeine92** [comment]
Hello,
Can I connect with you via Discord to explain barriers and challenges using your Guide, and possibly recommend improvements for other new users?

I am also available on other instant Chat's. I am interested in ensuring your guide is friendly for other clients in my position.

Than you,
------- Original Message -------

**Comment by mrkaffeine92** [comment]
Btw, Python38 does not install on Ubuntu 20.04 (latest) per Intstructions. Prior 3.6 oly runs
------- Original Message -------

**Comment by mrkaffeine92** [comment]
Please be advised, after:

sudo pip3 install ansible

There is no

vars/default.yml

Neither a vars folder. Only /var/
------- Original Message -------

**Comment by ahembree** [comment]
I've created a discord channel with this temporary invite: https://discord.gg/Abs2XVf8

The `vars` folder is within the project folder, you need to `cd ansible-hms-docker` after cloning.

**Comment by mrkaffeine92** [comment]
Please close ticket. Author did not allow review of current setup and .yml file after continued support request.
------- Original Message -------

**Comment by ahembree** [comment]
As a security researcher, I do not accept files from unknown 3rd parties, I hope you can understand.

I offered you to send the text content via Discord, but you declined.

**Comment by mrkaffeine92** [comment]
The .yml file would obviously uploaded to PasteBin as text file for your review instead of assumption.
Please kindly document Author resignation from project as well as support insufficiency after request. You did not allow any kind of data troubleshooting and assumed it was virus.
--As I have stated, I am noob and furthermore, this is extreme disconcerning coming from Author.
Thank you,
------- Original Message -------

**Comment by mrkaffeine92** [comment]
Following up on request.
-Ofc. you have closed it without taking look into errors users encountered.

**Comment by ahembree** [comment]
I closed it just as you requested:

> Please close ticket.

I'm sorry that I did assume it would be via a file share and not pastebin. However, knowing the structure of the compose file, you may accidentally upload API keys and secrets to pastebin unless you redacted them manually. I'm working on resolving this secrets issue.

If you would like to redact your compose file and send it via pastebin, I will take a look at it, but a compose file will not be able to show me issues with API keys or configuration specific to your environment.

**Comment by mrkaffeine92** [comment]
Hello,
The pastebin with secret share files would obviously be only available to you -- how else would you diagnose client issues?

I have kindly requested Dedicated-Service closure due to non-compliance (help) with the mentioned file.

Please take this into consideration when trouble-shooting future versions of your Docker (which you should always entertain, not sure why you got spooked during Christmas, but none-the-less , happy Holidays without the work I guess.)

Good Day,

------- Original Message -------

**Comment by ahembree** [comment]
Perhaps there's a misunderstanding on what this project provides.

This project does not provide support on setting up your environment. This is a free, open-source project so I technically do not have "clients". I am under no obligation to provide help with setting up your environment unless there's an underlying issue with the project causing something to fail, and unfortunately obtaining and using API keys correctly is not something within that scope.

This project is also not directly related to the official Docker project, this project uses containers running on Docker to provide the services.

Again, you are welcome to send me a pastebin link, but I don't believe I'll ultimately be able to help if the issue is with your API keys.

**Comment by mrkaffeine92** [comment]
hello,

If you have uploaded a Github project, I suppose you are obligated to keep it up to date.
I have done a good-will offer to request support and you have denied.

Please make it known that you do not support the project fully.

I have offered access to logs, Server, and DNS
And your response was minimal and not in accordance.

Kindly,
------- Original Message -------

**Comment by mrkaffeine92** [comment]
Please see attachment for Dedi-cancellation due to Support provided.
Ma future CLIENTS SEE THIS.
------- Original Message -------

**Comment by ahembree** [comment]
Keeping the project up to date, which I do and you can verify by commit history, is not synonymous with providing support on setting up your environment.

I'm not sure what you're referring to about "Dedi-cancellation" as there's nothing to cancel about this project, it is open-source and free to use.

**Comment by mrkaffeine92** [comment]
You may keep it updated but the Support is below-par for a new Person who has not only requested clarification but also Help because your Tutorial obviously has holes.
Thanks
