### ISSUE TITLE
Makefile uses [[ but is called via sh

### ISSUE THREAD

**Issue by TiiFuchs** [ahembree/ansible-hms-docker#34]
On Debian 12 I get the following error while running make:

```
make advanced
⚠ This will overwrite all existing files in './vars/custom', are you sure? [y/n] > /bin/sh: 2: read: arg count
/bin/sh: 3: [[: not found
[OK] Copying files...
```

The Makefiles statements are run with /bin/sh (apparently) but [[ is only available with bash etc.

**Comment by ahembree** [comment]
Thanks for the report! This has been resolved in https://github.com/ahembree/ansible-hms-docker/commit/18d36f400c17eb4f64cbb8e81e06b30ff64d1705
