### ISSUE TITLE
Unexpected keyword argument - ssl_version.

### ISSUE THREAD

**Issue by fobiat** [ahembree/ansible-hms-docker#48]
I've tried to run the playbook with both ssl enabled and disabled.
It hangs on the following error, I've trawled through the config files and cannot find a reference to ssl_version, unless I missed it.
Ubuntu server LTS, fresh install but fully up-to-date.

```
TASK [hmsdocker : Ensure env] ***************************************************************************************************************************
ok: [localhost]

TASK [hmsdocker : Ensure docker-compose.yml file.] ******************************************************************************************************
ok: [localhost]

TASK [hmsdocker : Ensure containers defined in compose file.] *******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration error - kwargs_from_env() got an unexpected keyword argument 'ssl_version'"}

PLAY RECAP **********************************************************************************************************************************************
localhost                  : ok=24   changed=0    unreachable=0    failed=1    skipped=44   rescued=0    ignored=0   
```

**Comment by fobiat** [comment]
I am using 22.04 yes

**Comment by ahembree** [comment]
This appears to be an issue with the docker python module, which unfortunately is out of my control so we can only wait for a patch: https://github.com/docker/docker-py/issues/3194#issuecomment-1848950456

If you run `sudo pip3 freeze | grep docker`, you should see that the `docker` version is `7.0.0`, which is the one that is broken. You can downgrade to the version that works by running `sudo pip3 uninstall docker` and then `sudo pip3 install docker==6.1.3`. I'll be updating the code to install this specific version shortly.

**Comment by ahembree** [comment]
This should now be resolved in https://github.com/ahembree/ansible-hms-docker/commit/d6a55b2638bf1e30ef244ae1a9c786b5dc16418e. Run `git pull` while in the `ansible-hms-docker` folder to get the update
