### ISSUE TITLE
Anyway to mount multiple shares?

### ISSUE THREAD

**Issue by KlutzyBubbles** [ahembree/ansible-hms-docker#61]
I keep movies and tvshows on seperate smb shares,, and browsing through this playbook it looks like you can only mount 1 share which then gets used to create multiple folders inside that share. Having multiple shares seems like something that isn't just an edgecase.

Are there any plans to implement this?

**Comment by ahembree** [comment]
I believe this is actually implemented, though I haven't really tested with SMB shares, I currently have it setup with NFS.

You have to use the advanced config, and then configure the `nas_additional.yml` file, the instructions are in that file as well, but feel free to comment here again if you have any issues.

**Comment by KlutzyBubbles** [comment]
In classic issue creating fashion, i have solved the issue a few minutes after opening it. I think i found the file that has the configs for additional configs :/

And damn that is the fastest response i have ever seen on an issue.
