### ISSUE TITLE
ERROR: Error response from daemon: Container is restarting, wait until the container is running

### ISSUE THREAD

**Issue by St-rgazer** [ahembree/ansible-hms-docker#67]
Getting this error while trying to apply

TASK [hmsdocker : Get public IP from Transmission VPN container.] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["docker", "exec", "transmission", "curl", "-s", "icanhazip.com"], "delta": "0:00:00.012615", "end": "2024-05-10 17:25:08.981082", "msg": "non-zero return code", "rc": 1, "start": "2024-05-10 17:25:08.968467", "stderr": "Error response from daemon: Container 06f3a5e442579ae024a0e61fe54fe92ced31ad9a2dec096b69006bf9e290468e is restarting, wait until the container is running", "stderr_lines": ["Error response from daemon: Container 06f3a5e442579ae024a0e61fe54fe92ced31ad9a2dec096b69006bf9e290468e is restarting, wait until the container is running"], "stdout": "", "stdout_lines": []}

**Comment by ahembree** [comment]
Appears to be an issue with the Transmission container starting or crashing and restarting itself. I'd verify your VPN credentials and/or config is correct and try again.

You may be able to see what logs the container is outputting by running `sudo docker logs -f transmission`, this could help narrow down the exact issue the container is having.
