### ISSUE TITLE
Failed to install docker-compose

### ISSUE THREAD

**Issue by joelanguera** [ahembree/ansible-hms-docker#79]
OS: Ubuntu 24.04 LTS
Ansible: core 2.17.1
Docker: 26.1.4

Just a fresh Ubuntu 24.04 Server installation, just ran:
`sudo apt install git make python3-pip -y`
`sudo pip3 install ansible`
`sudo mv /usr/lib/python3.12/EXTERNALLY-MANAGED /usr/lib/python3.12/EXTERNALLY-MANAGED.old`
Then cloned the repo, configured and `make apply`
It fails on:
TASK [galaxy-roles/geerlingguy.pip : Ensure pip_install_packages are installed.]
It is able to install `docker` but fails to install `docker-compose`
Looks like there is a [issue](https://github.com/docker/compose/issues/11168) with the `PyYAML` version used [5.4.1] and the installation of `docker-compose`.

I managed to get the `docker-compose` installed by manually installing an older version of `PyYAML`. Then removed the `docker-compose` installation from the playbook and the run finally succeeded.

**Comment by ahembree** [comment]
This appears to be an issue with the `geerlingguy.pip` package, which is not managed by this repo.
There's an open issue for Ubuntu 24.04 LTS: https://github.com/geerlingguy/ansible-role-pip/issues/66

The above page will then you lead here, so try the steps here: https://github.com/geerlingguy/ansible-role-pip/issues/57

**Comment by joelanguera** [comment]
It is a different issue, there is the issue regarding the `This environment is externally managed` which happens with the installation of docker, as it's the first package to install, but then it also fails on the `docker-compose` installation due to incompatibility with the PyYAML version used..
Closing this now though as it's not related with this repo. Thanks!

**Comment by joelanguera** [comment]
Looks like the long term fix would be to use `docker compose` v2 instead of the old `docker-compose` v1. I do not know the implications of using one vs the other and if it should be considered in this repo, the other one "geerlingguy/ansible-role-pip" or both

**Comment by joelanguera** [comment]
You can actually just remove the `docker-compose` installation from pip_install_packages on `hms-docker.yml` and the run goes fine. (I only had plex, sonarr and radarr though)

**Comment by ahembree** [comment]
I switched the ansible compose module to the [docker_compose_v2 module](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html) a while ago, so I'll look into if the pip package is still needed or not, thanks for digging into it!

**Comment by KnuffigerMaxi** [comment]
pls fix

**Comment by ahembree** [comment]
this has been fixed in https://github.com/ahembree/ansible-hms-docker/pull/81
